name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_backend:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    defaults:
      run:
        working-directory: ./backend/src

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./backend/src/yarn.lock
        
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install husky
        run: npm install -g husky
      - name: Install dependencies
        run: yarn
      - name: Run tests
        id: backend_tests
        run: yarn test

  build_frontend:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    defaults:
      run:
        working-directory: ./frontend/src

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./frontend/src/yarn.lock
        
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install husky
        run: npm install -g husky
      - name: Install dependencies
        run: yarn
      - name: Run tests
        id: frontend_tests
        run: yarn run cy:e2e-headless